### ISSUE TITLE
Adding small image into a blog or news article doesnt actually add the small version of the image.

### ISSUE THREAD

**Issue by WraithActual** [HoodDigital/Hood#6]

**Comment by JorjeRedemption** [comment]
Found out why this is, i added a field in the Media Settings to add a Hood API key, this allows the system to do the thumbnailing - if it isn't set, then the site doesn't thumbnail, and just adds the full size image to all the image size slots.

**Comment by JorjeRedemption** [comment]
Adding a patch to update the media settings page in the next commit.
